name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux (Flatpak)
        - Linux (deb)
        - Linux (rpm)
        - Linux (AUR)
        - Linux (Build from source)
        - macOS (DMG)
        - macOS (Mac App Store)
        - macOS (Build from source)
        - Windows (Installer)
        - Windows (Microsoft Store)
        - Windows (Build from source)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: e.g., Ubuntu 24.04, macOS 15.2, Windows 11 23H2
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: desktop
    attributes:
      label: Desktop Environment
      placeholder: e.g., GNOME 47, KDE Plasma 6

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Run `see` from terminal and paste any error output here.
      render: shell
