name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Describe the problem you're trying to solve or the use case for this feature.
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - URL Shortening
        - Text Sharing
        - File Upload
        - QR Code
        - UI/UX
        - Settings/Preferences
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Mockups or Screenshots
      description: If applicable, add mockups or screenshots to illustrate your idea.
